### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by fallXone** [comment]
Would it be possible to get this merged? Would like to use this with Grunt 1.0

**Comment by kkemple** [comment]
i haven't used grunt or this plugin for quite some time, i'm looking for someone to take it over, are interested? or do you know anyone who is? I just don't have the time. I will also update readme to reflect that

**Comment by fallXone** [comment]
Hi.  Unfortunately I don't know a lot about grunt either, so I wouldn't be
interested in maintaining. However it would just be a quick fix to the
package.json if you would be willing to do that? You just have to change
the grunt dependency in package.json from "grunt": "~0.4.1" to "grunt":
">=0.4.0" and then publish a new release on npm. You can ignore the rest of
that pull request. Then this will work with the latest version of grunt,
and nothing will break because of it.

**Comment by kkemple** [comment]
@fallXone i released a new version with support for Grunt 1.0

**Comment by fallXone** [comment]
Great thank you very much!

**Pull request closed without merging**
